---
version: "3.4"

services:
  mysql:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=revive
      - MYSQL_DATABASE=revive
      - MYSQL_USER=revive
      - MYSQL_PASSWORD=revive
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
